/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : TST_MEMMAP.H                                          */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : Valeo                                                   */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 VALEO                                                       */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* PVCS Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 05/07/14, 16:50:16: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* Project section mappings */
/* !Comment: TST Section allocation */
#elif defined   TST_START_SEC_TST_VAR
   #undef  TST_START_SEC_TST_VAR
   #define START_SEC_TST_VAR_SECTION
#elif defined   TST_STOP_SEC_TST_VAR
   #undef  TST_STOP_SEC_TST_VAR
   #define STOP_SEC_TST_VAR_SECTION

#elif defined   TST_START_SEC_TST_CODE
   #undef  TST_START_SEC_TST_CODE
   #define START_SEC_TST_CODE_SECTION
#elif defined   TST_STOP_SEC_TST_CODE
   #undef  TST_STOP_SEC_TST_CODE
   #define STOP_SEC_TST_CODE_SECTION

#elif defined   TST_START_SEC_TST_CALIB
   #undef  TST_START_SEC_TST_CALIB
   #define START_SEC_TST_CALIB_SECTION
#elif defined   TST_STOP_SEC_TST_CALIB
   #undef  TST_STOP_SEC_TST_CALIB
   #define STOP_SEC_TST_CALIB_SECTION

#elif defined   TST_START_SEC_TST_CONST
   #undef  TST_START_SEC_TST_CONST
   #define START_SEC_TST_CONST_SECTION
#elif defined   TST_STOP_SEC_TST_CONST
   #undef  TST_STOP_SEC_TST_CONST
   #define STOP_SEC_TST_CONST_SECTION

#elif defined   TST_START_SEC_TST_VAR_REPROG_REQ
   #undef  TST_START_SEC_TST_VAR_REPROG_REQ
   #define START_SEC_TST_VAR_REPROG_REQ_SECTION
#elif defined   TST_STOP_SEC_TST_VAR_REPROG_REQ
   #undef  TST_STOP_SEC_TST_VAR_REPROG_REQ
   #define STOP_SEC_TST_VAR_REPROG_REQ_SECTION

#elif defined   TST_START_SEC_TST_VER_MAPPING
   #undef  TST_START_SEC_TST_VER_MAPPING
   #define START_SEC_TST_VER_MAPPING_SECTION
#elif defined   TST_STOP_SEC_TST_VER_MAPPING
   #undef  TST_STOP_SEC_TST_VER_MAPPING
   #define STOP_SEC_TST_VER_MAPPING_SECTION


#endif

/* ECU specific section mappings */
#ifndef MEMMAP_START_DONE

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_TST_VAR Start Section treatment */
   #elif defined   START_SEC_TST_VAR_SECTION
	  

      #pragma section ".data_cpu1" aw

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_TST_CODE Start Section treatment */
   #elif defined   START_SEC_TST_CODE_SECTION
	  

      #pragma section ".text" ax

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_TST_CALIB Start Section treatment */
   #elif defined   START_SEC_TST_CALIB_SECTION
	  

      #pragma section ".calib" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_TST_CONST Start Section treatment */
   #elif defined   START_SEC_TST_CONST_SECTION
	  

      #pragma section ".const" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_TST_VAR_REPROG_REQ Start Section treatment */
   #elif defined   START_SEC_TST_VAR_REPROG_REQ_SECTION
	  

      #pragma section ".data_cpu1" aw

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_TST_VER_MAPPING Start Section treatment */
   #elif defined   START_SEC_TST_VER_MAPPING_SECTION
	  

      #pragma section ".text" ax

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE


   #endif

#else   /* if MEMMAP_START_DONE is not defined */

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_TST_VAR Stop Section treatment */
   #elif defined   STOP_SEC_TST_VAR_SECTION && defined  START_SEC_TST_VAR_SECTION
	  

      #pragma section

      #undef START_SEC_TST_VAR_SECTION
      #undef STOP_SEC_TST_VAR_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_TST_CODE Stop Section treatment */
   #elif defined   STOP_SEC_TST_CODE_SECTION && defined  START_SEC_TST_CODE_SECTION
	  

      #pragma section

      #undef START_SEC_TST_CODE_SECTION
      #undef STOP_SEC_TST_CODE_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_TST_CALIB Stop Section treatment */
   #elif defined   STOP_SEC_TST_CALIB_SECTION && defined  START_SEC_TST_CALIB_SECTION
	  

      #pragma section

      #undef START_SEC_TST_CALIB_SECTION
      #undef STOP_SEC_TST_CALIB_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_TST_CONST Stop Section treatment */
   #elif defined   STOP_SEC_TST_CONST_SECTION && defined  START_SEC_TST_CONST_SECTION
	  

      #pragma section

      #undef START_SEC_TST_CONST_SECTION
      #undef STOP_SEC_TST_CONST_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_TST_VAR_REPROG_REQ Stop Section treatment */
   #elif defined   STOP_SEC_TST_VAR_REPROG_REQ_SECTION && defined  START_SEC_TST_VAR_REPROG_REQ_SECTION
	  

      #pragma section

      #undef START_SEC_TST_VAR_REPROG_REQ_SECTION
      #undef STOP_SEC_TST_VAR_REPROG_REQ_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_TST_VER_MAPPING Stop Section treatment */
   #elif defined   STOP_SEC_TST_VER_MAPPING_SECTION && defined  START_SEC_TST_VER_MAPPING_SECTION
	  

      #pragma section

      #undef START_SEC_TST_VER_MAPPING_SECTION
      #undef STOP_SEC_TST_VER_MAPPING_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE


   #endif
#endif

#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into TST_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

