#if !defined(SCHM_ECUM_H)
#define SCHM_ECUM_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file is the Module Interlink Header which contains the declarations relevant for that instance of a basic software module.
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.86
  * on Thu Oct 01 19:16:36 GMT+02:00 2015. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <SchM_EcuMType.h>      /* SchM type header file */

/*==================[inclusions]=============================================*/

/*==================[macros]=================================================*/

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/
/*
#define RTE_START_SEC_CODE
#include "MemMap.h"

extern FUNC(void, RTE_CODE) SchM_Enter_EcuM_SCHM_ECUM_EXCLUSIVE_AREA_0(void);

extern FUNC(void, RTE_CODE) SchM_Exit_EcuM_SCHM_ECUM_EXCLUSIVE_AREA_0(void);

#define RTE_STOP_SEC_CODE
#include "MemMap.h"

#define ECUM_START_SEC_CODE
#include "MemMap.h"
extern FUNC(void, ECUM_CODE) EcuM_MainFunction(void);

#define ECUM_STOP_SEC_CODE
#include "MemMap.h"
*/
/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
/** @} doxygen end group definition */
#endif /* !defined(SCHM_ECUM_H) */
/*==================[end of file]============================================*/

