#if !defined(SCHM_CANIF_H)
#define SCHM_CANIF_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file is the Module Interlink Header which contains the declarations relevant for that instance of a basic software module.
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Tue Nov 18 09:39:35 CET 2014. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "SchM_CanIfType.h"      /* SchM type header file */

/*==================[inclusions]=============================================*/
#include "Os.h"

/*==================[macros]=================================================*/

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

#define SchM_Enter_CanIf_SCHM_CANIF_EXCLUSIVE_AREA_0() SuspendAllInterrupts()
#define SchM_Exit_CanIf_SCHM_CANIF_EXCLUSIVE_AREA_0()  ResumeAllInterrupts()

#define CANIF_START_SEC_CODE
#include "MemMap.h"
#define CANIF_STOP_SEC_CODE
#include "MemMap.h"

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
/** @} doxygen end group definition */
#endif /* !defined(SCHM_CANIF_H) */
/*==================[end of file]============================================*/

