#if !defined(SCHM_COM_H)
#define SCHM_COM_H

/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2013 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

 /*
  * This file is the Module Interlink Header which contains the declarations relevant for that instance of a basic software module.
  *
  * This file has been automatically generated by
  * EB tresos AutoCore Rte Generator Version 6.1.75
  * on Tue Nov 18 09:39:35 CET 2014. !!!IGNORE-LINE!!!
  */

 /* \addtogroup Rte Runtime Environment
  * @{ */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "SchM_ComType.h"      /* SchM type header file */
#include "Os.h"
/*==================[inclusions]=============================================*/

/*==================[macros]=================================================*/

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

#define SchM_Enter_Com_SCHM_COM_EXCLUSIVE_AREA_0() SuspendAllInterrupts()
#define SchM_Exit_Com_SCHM_COM_EXCLUSIVE_AREA_0() ResumeAllInterrupts()
#define SchM_Enter_Com_SCHM_COM_EXCLUSIVE_AREA_1() SuspendAllInterrupts()
#define SchM_Exit_Com_SCHM_COM_EXCLUSIVE_AREA_1() ResumeAllInterrupts()

#define COM_START_SEC_CODE
#include "MemMap.h"
extern FUNC(void, COM_CODE) Com_MainFunctionRx(void);

extern FUNC(void, COM_CODE) Com_MainFunctionTx(void);

#define COM_STOP_SEC_CODE
#include "MemMap.h"

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
/** @} doxygen end group definition */
#endif /* !defined(SCHM_COM_H) */
/*==================[end of file]============================================*/

